openapi: 3.0.3
info:
  title: API de gestion d'utilisateur
  description: API pour recuperer une liste d'utilisateur  avec pagination.
  version: 1.0.0
servers:
  - url: https://api.example.com/v1
    description: serveur principal
paths:
  /users:
    get:
      summary: Recuperer une liste d'utilisateur
      description: Recupere une liste paginee d'utilisateurs n fonction des parametres page et size
      operationId: getUsers
      parameters:
        - name: page
          in: query
          description: Numero de la page a recuperer
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 200
            default: 20
      responses:
        '200':
          description: Listes des utilisateur trouves
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref:
        '400':
          description: Mauvais types de parametres fournis
          content:
            application/json:
              schema:
                $ref:
  components:
    schemas:
      User:
        type: object
        properties:
          id:
            type: integer
            example: 1
          name:
            type: string
            example: Alice
          email:
            type: string
            format: email
            example: alice@examle.com
        required:
          id
          name
          email
      Error:
        type: object
        properties:
          error:
            type: string
            example: Bad types for provided query parameters
        required:
          error